name: CI

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: unittest
        run: python -m unittest discover tests
